all:
	gcc fork_loop.c -o fork_loop
	gcc fork_long_tail.c -o fork_long_tail
	gcc fork_binary.c -o fork_binary
	gcc fork_stochastic.c -o fork_stochastic
	gcc fork_bomb.c -o fork_bomb

clean:
	rm fork_loop
	rm fork_long_tail
	rm fork_binary
	rm fork_stochastic
	rm fork_bomb

